apiVersion: "mlkube.io/v1beta1"
kind: "TfJob"
metadata:
  name: "example-job"
spec:
  tensorboard:
    logDir: /tmp/tensorflow
    serviceType: LoadBalancer
    volumes:
      - name: azurefile
        azureFile:
            secretName: azure-secret
            shareName: data
            readOnly: false
    volumeMounts:
      - mountPath: /tmp/tensorflow
        name: azurefile
  replicaSpecs:
    - replicas: 1
      tfPort: 2222
      tfReplicaType: MASTER
      template:
        spec:
          volumes:
            - name: azurefile
              azureFile:
                  secretName: azure-secret
                  shareName: data
                  readOnly: false
          containers:
            - image: wbuchwalter/helm-tf:hyper-param-sweep-cpu
              name: tensorflow
              command:
                - python
                - main.py
                - --log-dir
                - /tmp/tensorflow/
              env:
                - name: LC_ALL
                  value: C.UTF-8
              volumeMounts:
                - mountPath: /tmp/tensorflow
                  name: azurefile
          restartPolicy: OnFailure